name: funk-control

services:
  postgres:
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  minio:
    ports:
      - "${MINIO_HOST_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_HOST_PORT:-9001}:9001"

  auth:
    ports:
      - "${AUTH_HOST_PORT:-4001}:${AUTH_PORT:-4001}"

  storage:
    ports:
      - "${STORAGE_HOST_PORT:-4002}:${STORAGE_PORT:-4002}"
